version: "3"

services:
  db-postgres-portfolio:
    image: postgres:alpine
    ports:
      - "5435:5432"
    container_name: "db-postgres-portfolio"
    restart: always
    volumes:
      - ./banco-de-dados-portfolio-api:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

volumes:
  db:
    driver: local
